// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCRwp4o6z-hgaH6HJk3dFvugUaPHi4cM',
    appId: '1:862502702642:web:85335486db80eb4aa1b62b',
    messagingSenderId: '862502702642',
    projectId: 'fir-test-975cf',
    authDomain: 'fir-test-975cf.firebaseapp.com',
    databaseURL: 'https://fir-test-975cf-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-975cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzY6C4Azm1bxuY2KSGgIvMqXCR_3fpcc',
    appId: '1:862502702642:android:5d259e5721bbae0fa1b62b',
    messagingSenderId: '862502702642',
    projectId: 'fir-test-975cf',
    databaseURL: 'https://fir-test-975cf-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-975cf.appspot.com',
  );
}
